import { Verb, Category } from './types';

export const ALL_VERBS: Verb[] = [
  // General Actions (1-21)
  { id: 1, english: "Add", spanish: "Añadir", category: Category.GENERAL },
  { id: 2, english: "Be", spanish: "Ser/Estar", category: Category.GENERAL },
  { id: 3, english: "Bring", spanish: "Traer", category: Category.GENERAL },
  { id: 4, english: "Can", spanish: "Poder", category: Category.GENERAL },
  { id: 5, english: "Change", spanish: "Cambiar", category: Category.GENERAL },
  { id: 6, english: "Come", spanish: "Venir", category: Category.GENERAL },
  { id: 7, english: "Do", spanish: "Hacer", category: Category.GENERAL },
  { id: 8, english: "Find", spanish: "Encontrar", category: Category.GENERAL },
  { id: 9, english: "Finish", spanish: "Terminar", category: Category.GENERAL },
  { id: 10, english: "Get", spanish: "Conseguir", category: Category.GENERAL },
  { id: 11, english: "Go", spanish: "Ir", category: Category.GENERAL },
  { id: 12, english: "Give", spanish: "Dar", category: Category.GENERAL },
  { id: 13, english: "Have", spanish: "Tener", category: Category.GENERAL },
  { id: 14, english: "Happen", spanish: "Suceder", category: Category.GENERAL },
  { id: 15, english: "Make", spanish: "Hacer (Crear)", category: Category.GENERAL },
  { id: 16, english: "Meet", spanish: "Encontrar/Conocer", category: Category.GENERAL },
  { id: 17, english: "Start", spanish: "Empezar", category: Category.GENERAL },
  { id: 18, english: "Stop", spanish: "Parar", category: Category.GENERAL },
  { id: 19, english: "Take", spanish: "Tomar", category: Category.GENERAL },
  { id: 20, english: "Try", spanish: "Intentar", category: Category.GENERAL },
  { id: 21, english: "Use", spanish: "Usar", category: Category.GENERAL },

  // Speaking (22-31)
  { id: 22, english: "Ask", spanish: "Preguntar", category: Category.SPEAKING },
  { id: 23, english: "Call", spanish: "Llamar", category: Category.SPEAKING },
  { id: 24, english: "Explain", spanish: "Explicar", category: Category.SPEAKING },
  { id: 25, english: "Listen", spanish: "Escuchar", category: Category.SPEAKING },
  { id: 26, english: "Lie", spanish: "Mentir", category: Category.SPEAKING },
  { id: 27, english: "Say", spanish: "Decir", category: Category.SPEAKING },
  { id: 28, english: "Speak", spanish: "Hablar", category: Category.SPEAKING },
  { id: 29, english: "Thank", spanish: "Agradecer", category: Category.SPEAKING },
  { id: 30, english: "Translate", spanish: "Traducir", category: Category.SPEAKING },
  { id: 31, english: "Understand", spanish: "Entender", category: Category.SPEAKING },

  // Thoughts & Emotions (32-54)
  { id: 32, english: "Agree", spanish: "Estar de acuerdo", category: Category.EMOTIONS },
  { id: 33, english: "Accept", spanish: "Aceptar", category: Category.EMOTIONS },
  { id: 34, english: "Believe", spanish: "Creer", category: Category.EMOTIONS },
  { id: 35, english: "Belong", spanish: "Pertenecer", category: Category.EMOTIONS },
  { id: 36, english: "Cry", spanish: "Llorar", category: Category.EMOTIONS },
  { id: 37, english: "Decide", spanish: "Decidir", category: Category.EMOTIONS },
  { id: 38, english: "Dream", spanish: "Soñar", category: Category.EMOTIONS },
  { id: 39, english: "Enjoy", spanish: "Disfrutar", category: Category.EMOTIONS },
  { id: 40, english: "Feel", spanish: "Sentir", category: Category.EMOTIONS },
  { id: 41, english: "Forget", spanish: "Olvidar", category: Category.EMOTIONS },
  { id: 42, english: "Guess", spanish: "Adivinar", category: Category.EMOTIONS },
  { id: 43, english: "Hate", spanish: "Odiar", category: Category.EMOTIONS },
  { id: 44, english: "Imagine", spanish: "Imaginar", category: Category.EMOTIONS },
  { id: 45, english: "Know", spanish: "Saber/Conocer", category: Category.EMOTIONS },
  { id: 46, english: "Laugh", spanish: "Reír", category: Category.EMOTIONS },
  { id: 47, english: "Like", spanish: "Gustar", category: Category.EMOTIONS },
  { id: 48, english: "Love", spanish: "Amar", category: Category.EMOTIONS },
  { id: 49, english: "Need", spanish: "Necesitar", category: Category.EMOTIONS },
  { id: 50, english: "Remember", spanish: "Recordar", category: Category.EMOTIONS },
  { id: 51, english: "Smile", spanish: "Sonreír", category: Category.EMOTIONS },
  { id: 52, english: "Think", spanish: "Pensar", category: Category.EMOTIONS },
  { id: 53, english: "Want", spanish: "Querer", category: Category.EMOTIONS },
  { id: 54, english: "Worry", spanish: "Preocuparse", category: Category.EMOTIONS },

  // Movement (55-68)
  { id: 55, english: "Close", spanish: "Cerrar", category: Category.MOVEMENT },
  { id: 56, english: "Dance", spanish: "Bailar", category: Category.MOVEMENT },
  { id: 57, english: "Drive", spanish: "Conducir", category: Category.MOVEMENT },
  // 58 is 'Go' duplicate in original list, mapped to Move or handled by ID 11. Using Move as 59 placeholder logic
  { id: 59, english: "Move", spanish: "Mover", category: Category.MOVEMENT },
  { id: 60, english: "Open", spanish: "Abrir", category: Category.MOVEMENT },
  { id: 61, english: "Pull", spanish: "Tirar", category: Category.MOVEMENT },
  { id: 62, english: "Push", spanish: "Empujar", category: Category.MOVEMENT },
  { id: 63, english: "Play", spanish: "Jugar", category: Category.MOVEMENT },
  { id: 64, english: "Run", spanish: "Correr", category: Category.MOVEMENT },
  { id: 65, english: "Swim", spanish: "Nadar", category: Category.MOVEMENT },
  { id: 66, english: "Travel", spanish: "Viajar", category: Category.MOVEMENT },
  { id: 67, english: "Visit", spanish: "Visitar", category: Category.MOVEMENT },
  { id: 68, english: "Walk", spanish: "Caminar", category: Category.MOVEMENT },

  // Daily Life (69-95)
  { id: 69, english: "Break", spanish: "Romper", category: Category.DAILY_LIFE },
  { id: 70, english: "Clean", spanish: "Limpiar", category: Category.DAILY_LIFE },
  { id: 71, english: "Cook", spanish: "Cocinar", category: Category.DAILY_LIFE },
  { id: 72, english: "Copy", spanish: "Copiar", category: Category.DAILY_LIFE },
  { id: 73, english: "Compare", spanish: "Comparar", category: Category.DAILY_LIFE },
  { id: 74, english: "Die", spanish: "Morir", category: Category.DAILY_LIFE },
  { id: 75, english: "Discover", spanish: "Descubrir", category: Category.DAILY_LIFE },
  { id: 76, english: "Drink", spanish: "Beber", category: Category.DAILY_LIFE },
  { id: 77, english: "Dry", spanish: "Secar", category: Category.DAILY_LIFE },
  { id: 78, english: "Eat", spanish: "Comer", category: Category.DAILY_LIFE },
  { id: 79, english: "Help", spanish: "Ayudar", category: Category.DAILY_LIFE },
  { id: 80, english: "Include", spanish: "Incluir", category: Category.DAILY_LIFE },
  { id: 81, english: "Kill", spanish: "Matar", category: Category.DAILY_LIFE },
  { id: 82, english: "Kiss", spanish: "Besar", category: Category.DAILY_LIFE },
  { id: 83, english: "Learn", spanish: "Aprender", category: Category.DAILY_LIFE },
  { id: 84, english: "Live", spanish: "Vivir", category: Category.DAILY_LIFE },
  { id: 85, english: "Look", spanish: "Mirar", category: Category.DAILY_LIFE },
  { id: 86, english: "Read", spanish: "Leer", category: Category.DAILY_LIFE },
  { id: 87, english: "See", spanish: "Ver", category: Category.DAILY_LIFE },
  { id: 88, english: "Sing", spanish: "Cantar", category: Category.DAILY_LIFE },
  { id: 89, english: "Sleep", spanish: "Dormir", category: Category.DAILY_LIFE },
  { id: 90, english: "Teach", spanish: "Enseñar", category: Category.DAILY_LIFE },
  { id: 91, english: "Touch", spanish: "Tocar", category: Category.DAILY_LIFE },
  { id: 92, english: "Wait", spanish: "Esperar", category: Category.DAILY_LIFE },
  { id: 93, english: "Wash", spanish: "Lavar", category: Category.DAILY_LIFE },
  { id: 94, english: "Work", spanish: "Trabajar", category: Category.DAILY_LIFE },
  { id: 95, english: "Write", spanish: "Escribir", category: Category.DAILY_LIFE },

  // Shopping (96-100)
  { id: 96, english: "Cost", spanish: "Costar", category: Category.SHOPPING },
  { id: 97, english: "Buy", spanish: "Comprar", category: Category.SHOPPING },
  { id: 98, english: "Pay", spanish: "Pagar", category: Category.SHOPPING },
  { id: 99, english: "Save", spanish: "Ahorrar", category: Category.SHOPPING },
  { id: 100, english: "Sell", spanish: "Vender", category: Category.SHOPPING }
];

export const CATEGORIES_LIST = [
  Category.GENERAL,
  Category.SPEAKING,
  Category.EMOTIONS,
  Category.MOVEMENT,
  Category.DAILY_LIFE,
  Category.SHOPPING
];